name: filter Branches and paths

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
    paths-ignore:
      - 'docs/**'

jobs:
  filter-check:
    runs-on: ubuntu-latest
    steps:
      - name: Display commits
        run: echo "This workflow passed the branch and path filters"
