name: filter worflow

on:
  push:
    branches:
      - main
    branches-ignore:
      - dev
    paths:
      - 'src/**'
    paths-ignore:
      - 'docs/**'
    tags:
      - 'v1.*'
jobs:
  filter-check:
    runs-on: ubuntu-latest
    steps:
      - name: Display commits
        run: echo "This workflows passed the filters"
